use std::collections::BTreeSet;

use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize)]
pub struct DependencyNotice {
    pub package: String,
    pub version: String,
    pub licenses: Vec<String>,
}

impl DependencyNotice {
    pub fn render_line(&self) -> String {
        let licenses = self.licenses.join(" OR ");
        format!("- {} {} — {}", self.package, self.version, licenses)
    }
}

pub fn normalize_licenses(licenses: Vec<String>) -> Vec<String> {
    let mut unique = BTreeSet::new();
    for license in licenses {
        let value = license.trim();
        if !value.is_empty() {
            unique.insert(value.to_string());
        }
    }
    unique.into_iter().collect()
}

pub fn render_project_notice(title: &str, entries: &[DependencyNotice]) -> String {
    let mut out = String::new();
    out.push_str("Third-Party Notices\n\n");
    out.push_str("Generated by stella-compliance.\n");
    out.push_str("Review the matching SBOM for the exact component metadata.\n\n");
    out.push_str(&format!("Project: {}\n", title));

    if entries.is_empty() {
        out.push_str("- No licensed third-party dependencies were found.\n");
        return out;
    }

    for entry in entries {
        out.push_str(&entry.render_line());
        out.push('\n');
    }
    out
}

pub fn render_repo_notice(sections: &[(String, Vec<DependencyNotice>)]) -> String {
    let mut out = String::new();
    out.push_str("Third-Party Notices\n\n");
    out.push_str("Generated by stella-compliance.\n");
    out.push_str("Each section is derived from the checked-in project and container SBOMs.\n");

    for (title, entries) in sections {
        out.push('\n');
        out.push_str(title);
        out.push('\n');
        if entries.is_empty() {
            out.push_str("- No licensed third-party dependencies were found.\n");
            continue;
        }
        for entry in entries {
            out.push_str(&entry.render_line());
            out.push('\n');
        }
    }

    out
}
